const CATEGORIES_TYPES = {
  FETCH_SEARCH_LIST: 'FETCH_SEARCH_LIST',
  FETCH_PREV_LIST: 'FETCH_PREV_LIST',
  PUSH_CATEGORIES_SLUG: 'PUSH_CATEGORIES_SLUG',
  POP_CATEGORIES_SLUG: 'POP_CATEGORIES_SLUG',
  FETCH_PARENT_CATEGORIES_SUCCESS: 'FETCH_PARENT_CATEGORIES_SUCCESS',
  FETCH_SUB_CATEGORIES_SUCCESS: 'FETCH_SUB_CATEGORIES_SUCCESS',
  FETCH_PARENT_CATEGORIES_START: 'FETCH_PARENT_CATEGORIES_START',
  FETCH_PARENT_CATEGORIES_FAILURE: ' FETCH_PARENT_CATEGORIES_FAILURE'
};

export default CATEGORIES_TYPES;
