const HOME_CATEGORIES_TYPES = {
  FETCH_SEARCH_LIST: 'HOME_FETCH_SEARCH_LIST',
  FETCH_PREV_LIST: 'HOME_FETCH_PREV_LIST',
  PUSH_CATEGORIES_SLUG: 'HOME_PUSH_CATEGORIES_SLUG',
  POP_CATEGORIES_SLUG: 'HOME_POP_CATEGORIES_SLUG',
  FETCH_PARENT_CATEGORIES_SUCCESS: 'HOME_FETCH_PARENT_CATEGORIES_SUCCESS',
  FETCH_SUB_CATEGORIES_SUCCESS: 'HOME_FETCH_SUB_CATEGORIES_SUCCESS',
  FETCH_PARENT_CATEGORIES_START: 'HOME_FETCH_PARENT_CATEGORIES_START',
  FETCH_PARENT_CATEGORIES_FAILURE: 'HOME_FETCH_PARENT_CATEGORIES_FAILURE',
  RESET_CATEGORIES_LIST: 'HOME_RESET_CATEGORIES_LIST'
};

export default HOME_CATEGORIES_TYPES;
