const CART_TYPES = {
  TOGGLE_CART: 'TOGGLE_CART',
  Add_TO_CART: 'ADD_TO_CART',
  FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
  FETCH_CART_START: 'FETCH_CART_START',
  FETCH_CART_FAILURE: 'FETCH_CART_FAILURE',
  INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
  DECREMENT_QUANTITY: 'DECREMENT_QUANTITY',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  GET_CART_TOTAL: 'GET_CART_TOTAL'
};

export default CART_TYPES;
