const WISH_LIST_TYPES = {
  ADD_TO_WISH_LIST: 'ADD_TO_WISH_LIST',
  FETCH_WISH_LIST_SUCCESS: 'FETCH_WISH_LIST_SUCCESS',
  FETCH_WISH_LIST_FAILURE: 'FETCH_WISH_LIST_FAILURE',
  FETCH_WISH_LIST_START: 'FETCH_WISH_LIST_START'
};

export default WISH_LIST_TYPES;
