const COLLECTION_TYPES = {
  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE',
  FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
  SELECT_CATEGORY: 'SELECT_CATEGORY',
  FETCH_HOME_COLLECTION_SUCCESS: 'FETCH_HOME_COLLECTION_SUCCESS',
  FETCH_FILTER_COLLECTION_SUCCESS: 'FETCH_FILTER_COLLECTION_SUCCESS',
  UPDATE_FILTER_OPTIONS: 'UPDATE_FILTER_OPTIONS',
  FETCH_HOME_COLLECTION_START: 'FETCH_HOME_COLLECTION_START',
  FETCH_HOME_COLLECTION_FAILURE: 'FETCH_HOME_COLLECTION_FAILURE',
  RESET_COLLECTION: 'RESET_COLLECTION'
};

export default COLLECTION_TYPES;
